spring.application.name=orm-learn

#application logs
logging.level.org.springframework = info
logging.level.com.cognizant = debug

# Hibernate logs for the SQL execution
logging.level.org.hibernate.SQL = trace
logging.level.org.hibernate.type.descriptor.sql = trace

# Logs format
logging.pattern.comsole = %d{dd-mm-yy} %d{hh:mm:ss.SSS} %-20.20thread %5p %-25.25logger{25} %25M %4L %m%n

#Database Configuration
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=root

#Hibernate config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect